"""empty message

Revision ID: 8d6680319e58
Revises: 6c3fded57ea3
Create Date: 2021-04-30 16:44:01.486593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6680319e58'
down_revision = '6c3fded57ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('librarian', sa.Column('profile_pic', sa.String(length=200), nullable=True))
    op.add_column('member', sa.Column('profile_pic', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'profile_pic')
    op.drop_column('librarian', 'profile_pic')
    # ### end Alembic commands ###
